import * as dotenv from 'dotenv';
dotenv.config();
import jwt from 'jsonwebtoken';

/**
 * This const defines the name to be used on the generated cookie that will store our JWT Tokens.
 * We gonna use tokens becase use Local Storage, despite being simpler, is potencialy unsecure.
 */
export const JWT_COOKIE_NAME = process.env.JWT_COOKIE_NAME as string;

/**
 * WARN:
 * 
 * Idealy this should be generated by a random hash generator and should be stored as ENV VAR.
 * But for this project we are avoiding use DOTENV just for fast deployment and easier setup
 * You can generate a new SECRET by runnin on node: require('crypto').randomBytes(64).toString('hex')
 */
export const JWT_SECRET = process.env.JWT_SECRET as string;

/**
 * WARN:
 * 
 * The generated token should expire in a couple hours, but this would drive us to a token refresher.
 * To save time we will use a long-live generated token, so we avoid the needing of a refresher now
 * saving time and complexity for both backend and frontend applications (simple challange tradeoff).
 */
export function encodeJWT(data: object) {
  return jwt.sign(data, JWT_SECRET, { expiresIn: '30d' });
}

/**
 * Verify a token that was generated using the encodeJWT function. If the cookie has been successfuly
 * decoded, this function will return the provided data that was encoded.
 */
export function decodeJWT(token: string) {
  return new Promise(resolve => {
    if (!token) {
      return resolve({ error: 'No token provided', data: null });
    }

    jwt.verify(token, JWT_SECRET, (error: any, data: any) => {
      error && console.error(error);

      resolve({ error, data });
    });
  });
}